
pages:
  stage: deploy
  image:
    name: registry.gitlab.com/taricorp/83pa28d/build:latest
    entrypoint: [""]
  script:
  - make DESTDIR=public
  artifacts:
    paths:
    - public
  only:
  - master
